# Find 10 reviews which have "dirty" in their reviews
import pymongo
import pprint
import datetime

client = pymongo.MongoClient("mongodb://localhost:27017/")
db = client["soen363"]
reviews = db["reviews"]

pipeline = [
    {"$match":
         {'comments':
              {'$regex': '/.*dirty.*/', '$options': 'i' }
          }
     },
    { "$group": { "_id": { "id": "$listing_id", "reviewer": "$reviewer_name", "comment": "$comments" }}},
    {"$limit":10}
]


a = datetime.datetime.now()
res = list(reviews.aggregate(pipeline))
b = datetime.datetime.now()

c = b - a
pprint.pprint(res)
pprint.pprint(str(c.microseconds * 0.001) + ' ms')

#Results
# [{'_id': {'comment': "Fenghui's place was very nice, spacious, and clean.  My "
#                      'friends and I love it and had a wonderful time in '
#                      'Toronto.  The metro/bus is very close and there are many '
#                      'places to eat nearby.   The neighborhood seemed safe and '
#                      'we had a wonderful trip.  The only issues we found were '
#                      'lack of toilet paper,  some dirty dishes, and the '
#                      "dog/child who we're upstairs we're a little noisy near "
#                      '10-11pm.  We would easily come back, especially based on '
#                      'the price we paid.',
#           'id': 19874568,
#           'reviewer': 'Mark'}},
#  {'_id': {'comment': "A great place if cleanliness is not an issue. Khadim's, "
#                      'place was in an ideal location and his communication was '
#                      'responsive and accurate, but the place was very dirty, '
#                      'especially the shower/tub and floors. The sheets were '
#                      'old, but washed. The comforter was dirty and had a '
#                      'rip/burn hole in it. The cleaning fees were very high so '
#                      'hopefully it gets cleaned proper after our visit. The '
#                      'roof top terrace is beautiful,  but there about 6 deck '
#                      'boards that are cut too short and you fall through the '
#                      'deck when you step on them, watch your step while '
#                      'enjoying the view! All that aside, I appreciate how '
#                      'polite and responsive Khadim was in all communications. '
#                      'Hopefully these issues are addressed as the place is in '
#                      'a great location and Khadim a solid host.',
#           'id': 34226304.0,
#           'reviewer': 'Garry'}},
#  {'_id': {'comment': 'This apartment is not suitable for human habitation '
#                      "because  it's (1) very hot, and the heater can't be "
#                      'controlled; the host provides a fan but it only makes '
#                      'things worse (see next point).  (2) very strong and bad '
#                      "odour, amplified further by the heat. If it's winter "
#                      'time and you open the balcony door for some air to help '
#                      'with heat/smell  you will damage your lungs (I did, '
#                      'couched and threw up after), (3) very dirty everywhere '
#                      '(gunk/hair around toilet, host left his used razors in '
#                      'the bathroom, discoloured couch cover, left over '
#                      'food/drinks in the fridge). I left this apartment a few '
#                      'hours after my late checkin even though it was pre-dawn, '
#                      "couldn't stay longer. The host also does not provide "
#                      "fresh towels but that would be the least of a visitor's "
#                      'concernts.',
#           'id': 22637175.0,
#           'reviewer': 'Ali'}},
#  {'_id': {'comment': 'DO NOT BOOK THIS AIRBNB. I have stayed in many places '
#                      'around the world and this is by far the absolute worst. '
#                      'For starters, entering the unit be prepared to be '
#                      'surround by webs/flies/spiders/moths etc. Aaryns home '
#                      'was not cleaned before we arrived - the couch was full '
#                      'of crumbs/dirt, the blankets were also dirty, and there '
#                      'were many “clean” dishes that were actually USED and '
#                      'still had food/residue on them. She tried to act as '
#                      'though she was fixing our problem by sending a cleaning '
#                      'lady to the unit at 7am without telling us what time to '
#                      'expect her arrival - in reality, this should have been '
#                      'handled BEFORE we checked in. The listing states that AC '
#                      'is included but it was conveniently broken during our '
#                      'entire stay (also 40 degree weather outside) and wasn’t '
#                      'fixed up until the evening before our checkout. We told '
#                      'Aaryn that we were out of toilet paper since she left 1 '
#                      'roll for 2 people for 4 days, she didn’t acknowledge it. '
#                      'There was no hand soap in the bathroom, she didn’t '
#                      'acknowledge it. She was horrible with communication and '
#                      'took HOURS to respond to messages and didn’t even answer '
#                      'phone calls. As guests we felt unwelcome and it was '
#                      'clear that there was no concern for us from her. All in '
#                      'all it was a pretty horrible stay and I would not '
#                      'recommend it unless you feel like wasting your money.',
#           'id': 9625109,
#           'reviewer': 'Shaquira'}},
#  {'_id': {'comment': 'This rental reminded me of a show property: it had shiny '
#                      'new items like the washer and dryer and soaking tub and '
#                      'lacked the lived in dirt that accumulates from the '
#                      'presence of people. However, there was dust caked onto '
#                      'the fans, spiderwebs in the corners and a lack of '
#                      'convenience items that indicate a long empty or unlived '
#                      'in home.\n'
#                      '\n'
#                      'There was no hand soap, in the bathroom or elsewhere, we '
#                      'made do with dish washing liquid. The tub while '
#                      'beautiful has no stopper - rendering it useless. There '
#                      'was no clothing detergent to use the washer. There were '
#                      'dirty/damp rags left in the dryer - still warm when we '
#                      'checked in around 8 pm so someone had been by to clean. '
#                      'The floors and living area surfaces were clean in the '
#                      'bedroom, bathroom and kitchen. I put a clean flat bed '
#                      'sheet over he couch to sit on it. It appeared very '
#                      'dirty/dusty. We did make some use of the tv and netflix. '
#                      'That was nice. It would be great to have the wifi '
#                      "password written on something in the house. I didn't "
#                      'realize it was sent with the listing, due to having to '
#                      'cancel another airbnb because it was dirty and rent this '
#                      'one in the middle of the night, and it took me a day to '
#                      'get wifi access elsewhere and find that information. The '
#                      'location was perfect. A short bike ride to old port, '
#                      'Notre Dame, Gay Village and slightly longer but pleasant '
#                      'ride to Olympic Park. Much longer to the Biosphere, '
#                      'unless you ride to old port and take the ferry. 2.5 '
#                      'blocks from a metro station safe to walk at all hours '
#                      'and quiet street. Much potential.',
#           'id': 24729953.0,
#           'reviewer': 'Vanessa'}},
#  {'_id': {'comment': 'WARNING - a real horror trip: I had two terrible nights '
#                      'at the place of Marie-Denise or Rosie (or „Princess“ ... '
#                      'how she is calling herself). I will surely never return '
#                      'and really cannot recommend this place. My mistake: I '
#                      'did plan and book very short-notice - there has not been '
#                      'a lot of options/alternatives left. I felt very '
#                      'uncomfortable at this place. All in one: spooky and '
#                      'scary. It is a pity that people hesitate to poste/write '
#                      'a realistic and honest evaluation/review (I could have '
#                      'been warned). But I do understand now because I have '
#                      'experienced it by myself: the host Marie-Denise is '
#                      'intimidating, manipulating and scaring her guests. It '
#                      'was so horrible and disgusting that I had a light '
#                      'allergic reaction and herpes after one night. After the '
#                      'first night I have tried to find another place to stay '
#                      'at but Quebec seemed to be fully booked out for the next '
#                      'days (due to a Celine Dion concert). I therefore decided '
#                      'just to close my eyes in order to somehow survive the '
#                      'second and last night, returned late and left very early '
#                      'the next morning. I should have noticed right in the '
#                      'beginning that there is something strange about this old '
#                      'lady, the host: she repeated several times (verbally and '
#                      'written) that she is doing this for 23 years and is '
#                      'having three legal permits for hosting guests. That was '
#                      'the first way to intimidate her guests („Do not dare to '
#                      'criticize me!“). Now, after reading all the reviews '
#                      'about her place, I could see that she was reacting very '
#                      'allergic on critics: 1) bad signal, 2) next hint on '
#                      'intimidation.\n'
#                      'The old house is not a charming and nice old/vintage '
#                      'house, it is more an old, dilapidated, stinking, not '
#                      'renovated house. It seems like Marie-Denise is not only '
#                      'intimidating her guests for 23 years, but also did never '
#                      'renovate the house, nor did she change the furniture or '
#                      'the rest of the equipment at this place. Some examples: '
#                      'Right at the entrance you are welcomed by a strange '
#                      'smell and a dusty/dirty/old carpet on the narrow stairs. '
#                      'Generally, musty and dusty place. The anti-slip '
#                      'bathtub-mat, that is supposed to be transparent, has an '
#                      'ugly brownish-yellowish and partly pinkish color. The '
#                      'bed sheet and pillow cases have stains. I had to remove '
#                      'five spiders from my bed in the first night. The odor in '
#                      'that house is a mixture of old people‘s home and urine. '
#                      'The other thing I did not like is that the guests do not '
#                      'get keys for that place. She leaves the house door '
#                      'unlocked - because Canada is safe  - even when she is '
#                      'not at home or during night. Plus no key/lock for the '
#                      'guest room. Old house - thin walls - every tiny move '
#                      'makes noise. Guest rooms are upstairs, second floor '
#                      '(narrow stairway), bathroom to be shared with four/five '
#                      'other guests. I know, Marie-Denise, this is in the '
#                      'description - I read it ... I just want to underline '
#                      'that your place is below the level of a very simple and '
#                      'cheap hostel - especially regarding the '
#                      'PRICE-PERFORMANCE RATIO. There are bad and good hotels, '
#                      'there are bad and good Airbnb places in the world - with '
#                      'a good and bad price-performance ratio. Your place is '
#                      'the worst I have ever experienced.  I am traveling a lot '
#                      '- I am able to compare and evaluate. Marie-Denise seems '
#                      'to be blind - she does not see that it is a shame what '
#                      'she is offering to her guests and she is not able to '
#                      'compare with other places/offers. Instead of '
#                      'noticing/realizing hat her walls need a renovation, she '
#                      'describes the walls, at least of my room, as „artistic '
#                      'walls“. Wow, describing yellow and grey stains/dirt as '
#                      'art is just crazy!!! She is absolutely amazed about '
#                      'herself. And yes, I have chosen to stay at Airbnb '
#                      'instead of staying at a hotel - yes, Marie-Denise, '
#                      'because of the costs - do not try mix-up facts: your '
#                      'place is terrible! The cherry on the the top of '
#                      'everything happened at the end: she sent me a message '
#                      'and gave me instructions how to evaluate her place/how '
#                      'to write a review. I was very thankful for her message - '
#                      'a written proof for her bad, strange and manipulative '
#                      'behavior/character - a proof of '
#                      'intimidation/manipulation. She wanted five stars and '
#                      'explains that a four star rating is bad. Honestly, '
#                      'Marie-Denise, wake up! I am not scared of you and your '
#                      'attempts of\n'
#                      'intimidation and manipulation do not work here.\n'
#                      'I have taken pictures of the above-mentioned points ... '
#                      'as a proof. A pity that there is no possibility to catch '
#                      'the odor at your place.\n'
#                      'The only good thing about Marie-Denise: She gave me a '
#                      'map of Quebec and some good tips and explanations on '
#                      'Quebec.\n'
#                      'I am so happy to have left this place!!\n'
#                      'Whilst checking the old reviews: I have noticed that '
#                      'every slight criticism of her guests is followed by a '
#                      'strange accuse from her side. I am aware of the fact '
#                      'that she will create something strange about me ... '
#                      'because I am criticizing Princess Rosie ... \n'
#                      'Marie-Denise, you deserve 0 stars!\n'
#                      'English is not my mother tongue but I hope everybody can '
#                      'understand the basics I am trying to communicate.\n'
#                      'If you do not plan/book short-notice as I did '
#                      '(unfortunately): take time, do research - there are a '
#                      'lot of other places with a better price-performance '
#                      'ratio in Quebec that really deserve four or five '
#                      'stars!!!\n'
#                      'All in one: \n'
#                      'WARNING - AVOID THIS PLACE!',
#           'id': 659635,
#           'reviewer': 'Zippy'}},
#  {'_id': {'comment': 'The condo is close to restaurants, shopping, parking but '
#                      "the photo's do not show how dirty the balcony is (patio "
#                      'furniture) and the rooftop penthouse also rusty / dirty '
#                      '/ disappointing. The bathroom was not cleaned when we '
#                      'arrived, so we cleaned it ourselves. The owner did offer '
#                      'to come and do it but we had done it by that point.',
#           'id': 7994914.0,
#           'reviewer': 'Rob'}},
#  {'_id': {'comment': 'Very uncomfortable/regrettable stay.  This, in fact, is '
#                      '1/2 of a basement on the 1/2 ground level. While the '
#                      'interior of the spaces matches the photos, what was not '
#                      'shown is the path that you have to walk thru to get to '
#                      'your basement apt entrance. After spending 10-15 min '
#                      'searching for a parking spot every night, you walk into '
#                      'a dark alley (about 10m), with smelly garbage dumped on '
#                      'both side of the alley. At / end of alley, turn left and '
#                      'you walk into 2 cars semi blocking the entrance to the '
#                      'basement units. There are woods and other dumps and '
#                      'garbage in the vicinity. There are spider webs that you '
#                      'will walk right into your face. You will have to squeeze '
#                      'thru 2 vehicles w/o dirtying your clothes before you get '
#                      'to  Ft dr #1. Unlock  dr #1, you walk into an unfinished '
#                      'hallway w/ woods piling in front of dr #2, which open '
#                      'into the basement apt. Imagine if you are dressed in '
#                      'some nice clothes, walking thru the above 3-4 times a '
#                      'day from the apt to yr car.  The place is very '
#                      'uncomfortable for following facts. 1. There is no '
#                      'bedboard, so you cannot sit up & read in bed. 2. The '
#                      'humidity in the unit is extremely high. There is a '
#                      'Dehumidifier put away in a small closet room, but we '
#                      'were not informed until we found it on the 2nd night. '
#                      'When i say extremely high, I meant you cannot even sit '
#                      'in the room w/o sweating. We use the dehumidifier (did '
#                      'not help much), and every 10 hrs or so, we need to empty '
#                      'a tank of water fr the dehumidifier tank before it '
#                      'overflows. 3. The outdoor temp at night after 9 pm '
#                      'during our stays (Aug 29-Sept 4) is < 20c. But the '
#                      'inside temp is at 28c. With the humidity and heat, we '
#                      'did not sleep for > 4 hrs per night. 4. On the 4th '
#                      'night, we found a fan (dusty and semi-working) in the '
#                      'closet room. It did little help after we have to wash '
#                      'off the dust on the fan. 5. We inform Ian that we are '
#                      'very uncomfortable & his reply was to buy a fan valued '
#                      'up to $40 and he will refund.  My message to Ian: Hi '
#                      'Ian. We are three nights into our stay and each night '
#                      'has been very uncomfortable. Even last night at 3am it '
#                      'was 28.5^C. Too warm, humid and hard to breathe. As we '
#                      'aren’t even able to open a window. Outside was under 20C '
#                      'Is there anything you can do to make or stay more '
#                      'tolerable. In addition to the comfortability issues, I '
#                      'also wanted to note a few things that are broken: The '
#                      'dryer handle The coffee machine ---------- Ian reply : '
#                      'Hello, maybe you can buy a fan up to 40$ that I would '
#                      'refund you? I have photos, videos to support my claim. '
#                      'Message me on F/b if anyone want to see.',
#           'id': 20071164.0,
#           'reviewer': 'Robert'}},
#  {'_id': {'comment': 'A regular guest who lives there tried to open my door '
#                      'repeatedly (and aggressively) at three in the morning. '
#                      'As well, there was noise from music and chatting at 8 '
#                      'a.m. thru till 3 / 4 a.m. on all three weekday nights I '
#                      'stayed there. The smell of weed was also pervasive to '
#                      'the point where I had to seek laundry and dry cleaning '
#                      'to maintain professionalism for work (since my clothes '
#                      'smelled strongly when I walked out). \n'
#                      '\n'
#                      "Because of the door situation, I wouldn't recommend this "
#                      'venue to those who are travelling alone and/or for a '
#                      'work trip. I felt very unsafe and threatened. Thankfully '
#                      'JJ was on site and intervened when issues arose, and he '
#                      'also ensured my safety. Appreciated the cleanliness of '
#                      'the bed but was unable to use the kitchenware or fridge '
#                      'as it was quite dirty (there were old tea bags inside '
#                      'the tea kettle that was for shared/common use).  \n'
#                      '\n'
#                      'JJ was a great host, but my experience was unpleasant '
#                      'for the entirety of the four days I stayed there. I felt '
#                      'so unsafe on the last night that I checked out at 6 a.m. '
#                      'on the first train the next morning. Would not stay here '
#                      'again.',
#           'id': 17175506,
#           'reviewer': 'Shazia'}},
#  {'_id': {'comment': 'We were a large group (10+ people) looking for last '
#                      "minute accommodations in the city. Jason's rental space "
#                      'seemed a good fit, as it was close to our event and '
#                      'there was enough rooms/beds to accommodate our group. '
#                      'However, the listing was not clear that the rental space '
#                      'would not be private. We found out after booking that we '
#                      'had in fact only booked rooms in the space and would be '
#                      'sharing the rental with other guests. The host, Jason, '
#                      'was 30+minutes late for our prearranged check-in time '
#                      'and we had to awkwardly enter the rental space alone and '
#                      'wait for him to arrive. Upon entering we encountered his '
#                      'family and it became obvious that the host and his '
#                      'family live in rental space and would present during our '
#                      'stay. Also, while we waited we found out that the host '
#                      'operates a music business and provides lessons at the '
#                      'rental space as students were coming and going. Before '
#                      'the host arrived we noticed that there were cameras '
#                      'located throughout the entire rental space. There was no '
#                      'indication in the listing that there would be '
#                      'surveillance devices present, nor did the host '
#                      'acknowledge them upon check-in. The overall cleanliness '
#                      'of the rental space was below standard and made us keep '
#                      'our use of the kitchen, bathrooms, and shared spaces to '
#                      'a minimum. In the kitchen there were used/dirty dishes '
#                      'from previous/current guests left in the sink, the '
#                      'garbage was full and the food waste bin was rotting, and '
#                      'there was a rotting food smell present. The toilets and '
#                      'showers were dirty and not cared for and no towels or '
#                      'toiletries were provided (even though the listing stated '
#                      '"essentials included.") There was evidence that not all '
#                      'the linens had been changed after previous guests, and '
#                      'personal toiletries from previous guests had been left '
#                      'behind in the bedrooms and not removed. Even though the '
#                      'space is a very large multi-level house with many rooms, '
#                      'it felt cramped and unwelcoming. Entire rooms, hallways, '
#                      'stairwells, and under-bed spaces were used for storage '
#                      'for drum sets and other musical instruments. There was '
#                      'also a strong marijuana smoke smell in the basement '
#                      'sleeping area where we stayed, even though the house '
#                      'rules stated “no smoking.” Our personal safety was of '
#                      'concern since the main door to the rental space was '
#                      'never locked and people (we hope they were other guests) '
#                      'were coming and going throughout our stay. We were also '
#                      'concerned for the safety of our personal belongings '
#                      'since there was no way to lock our bedrooms while we '
#                      'were away, even though other guests were staying at the '
#                      'rental space and people were coming and going all the '
#                      'time. We took all of our belongings with us while we '
#                      'were away throughout the day and into the evening. '
#                      'Finally, many of our group were unable to sleep as a '
#                      'large group of people (it is unknown if they were other '
#                      "guests or the host's family) were awake, and walking "
#                      'around, making excessive noise directly above and...',
#           'id': 17127422,
#           'reviewer': 'Heather'}}]
# '291.932 ms'